# Generated by Django 4.2.7 on 2024-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_country_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
